Update APK & IPA .yml

diff --git a/.github/workflows/APK & IPA .yml b/.github/workflows/APK & IPA .yml
--- a/.github/workflows/APK & IPA .yml
+++ b/.github/workflows/APK & IPA .yml
@@ -54,38 +54,41 @@ jobs:
         run: |
           export ORG_GRADLE_CACHING=false
           flutter build apk --release -v
+          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
+            echo "APK not found!"
+            exit 1
+        shell: bash
+
+      - name: List APK Directory
+        run: ls -R build/app/outputs/flutter-apk
 
       - name: Update CocoaPods
-        run: pod repo update
+        run: |
+          cd ios
+          pod repo update
+          pod install
         working-directory: ios
 
       - name: Build iOS App
         run: |
-          flutter build ios --no-codesign
+          flutter build ios --release --no-codesign
           cd build/ios/iphoneos
-          mkdir Payload
-          cd Payload
-          ln -s ../Runner.app
-          cd ..
-          zip -r Etqan.ipa Payload
+          zip -r Etqan.ipa Runner.app
 
-      - name: Check if APK exists
+      - name: Check if APK and IPA exist
         run: |
-          if [ ! -f build/app/outputs/apk/release/app-release.apk ]; then
+          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
             echo "APK not found!"
             exit 1
           fi
-
-      - name: Check if IPA exists
-        run: |
           if [ ! -f build/ios/iphoneos/Etqan.ipa ]; then
             echo "IPA not found!"
             exit 1
-          fi
+        shell: bash
 
       - name: Push to Releases
         uses: ncipollo/release-action@v1
         with:
-          artifacts: "build/app/outputs/apk/release/app-release.apk,build/ios/iphoneos/Etqan.ipa"
+          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios/iphoneos/Etqan.ipa"
           tag: v1.0.${{ github.run_number }}
           token: ${{ secrets.GITHUB_TOKEN }}
